<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */
?>
<?php $_order = $block->getOrder() ?>
<?php $payment = $_order->getPayment(); ?>
<?php $gateway = $payment->getMethodInstance(); ?>
<?php $information = $payment->getAdditionalInformation(); ?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= (int) $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?= ($_order->getIsVirtual() ? ' order-payment-method-virtual' : '') ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Payment Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= $block->getPaymentHtml() ?></div>
                <?php if (isset($information['request_id'])) { ?>
                    <div class="order-payment-method-request-id"><?= __('Request # %1', $information['request_id']) ?></div>
                <?php } ?>
                <?php if (isset($information['status_date'])) { ?>
                    <div class="order-payment-method-status-date"><?= __('Date: %1', $block->formatDate($information['status_date'], 2, 1)) ?></div>
                <?php } ?>
                <?php if (isset($information['status'])) { ?>
                    <div class="order-payment-method-status"><?= __('Status: ') . __($information['status']) ?></div>
                <?php } ?>
                <?php if (isset($information['status_message'])) { ?>
                    <div class="order-payment-method-status-message"><?= __('Reason: %1', $information['status_message']) ?></div>
                <?php } ?>
                <?php if (isset($information['process_url'])) { ?>
                    <?php $action = __('Finish payment'); ?>
                    <?php $status = new \Dnetix\Redirection\Entities\Status(['status' => isset($information['status']) ? $information['status'] : 'PENDING']); ?>
                    <?php if ($status->isApproved() || $status->isRejected()) { ?>
                        <?php $action = __('View payment details'); ?>
                    <?php } ?>
                    <div class="order-payment-method-process-url">
                        <a href="<?= $information['process_url']; ?>"><?= $action ?></a>
                    </div>
                <?php } ?>
                <?php if (isset($information['transactions']) && sizeof($information['transactions']) > 0) { ?>
                    <div class="order-payment-method-status-message"><?= __('Transactions:') ?></div>
                    <?php foreach ($information['transactions'] as $transaction) { ?>
                        <div><?= __($transaction['franchise']) . ' (CUS ' . $transaction['authorization'] . ') ' . __($transaction['status']) ?></div>
                    <?php } ?>
                <?php } ?>
                <div class="order-payment-currency"><?= $block->escapeHtml(__('The order was placed using %1.', $_order->getOrderCurrencyCode())) ?></div>
                <div class="order-payment-additional">
                    <?= $block->getChildHtml('order_payment_additional') ?>
                    <?= $block->getChildHtml('payment_additional_info') ?>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<?= $block->getChildHtml('order_additional_info') ?>

<?= $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Ordered')) ?></span>
    </div>
    <?= $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Notes for this Order')) ?></span>
            </div>
            <?= $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Order Totals')) ?></span>
            </div>
            <?= $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= $block->getChildHtml('popup_window') ?>

<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
</script>
