<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \PlacetoPay\Payments\Block\Frontend\Onepage\Success */ ?>
<?php $order = $block->getOrder(); ?>
<?php $payment = $order->getPayment(); ?>
<?php $information = $payment->getAdditionalInformation(); ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
        <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="placetopay-checkout-onepage">
        <?php if ($order) : ?>
            <?php if ($order->getStatus() == 'failed') : ?>
                <p><?= $block->escapeHtml(__('Unfortunately your order cannot be processed as the originating bank/merchant has declined your transaction. Please attempt your purchase again.')) ?></p>

                <?php if(isset($information['authorization'])) : ?>
                    <li>
                        <p><?= __('Authorization/CUS:') ?></p>
                        <p><?= $block->escapeHtml($information['authorization']) ?></p>
                    </li>
                <?php endif ?>
            <?php else : ?>
                <?php if (isset($information['process_url'])) : ?>
                    <p>
                        <?= $block->escapeHtml(
                            __(
                                '<br>For more information about the status of your order: <a href="%1" target="_blank">view order detail in placetopay</a>',
                                $information['process_url']
                            ), ['a']
                        ) ?>
                    </p>
                <?php endif ?>
                <ul class="order-details">
                    <li>
                        <p><?= __('Order status:') ?></p>
                        <p><?= $block->escapeHtml(__($information['status'])) ?></p>
                    </li>
                    <li>
                        <p><?= __('Date:') ?></p>
                        <p><?= $block->escapeHtml($block->dateFormat($information['status_date'], 'F d, Y, g:i a')) ?></p>
                    </li>
                    <li>
                        <p><?= __('Total Paid:') ?></p>
                        <p><?= $block->getFormattedPrice($order->getGrandTotal()) ?></p>
                    </li>
                    <li>
                        <p><?= __('Payment method:') ?></p>
                        <p><?= $block->escapeHtml($payment->getMethodInstance()->getTitle()) ?></p>
                    </li>
                    <?php if(isset($information['authorization'])) : ?>
                        <li>
                            <p><?= __('Authorization/CUS:') ?></p>
                            <p><?= $block->escapeHtml($information['authorization']) ?></p>
                        </li>
                    <?php endif ?>
                </ul>
            <?php endif ?>
        <?php else : ?>
        <?php endif ?>
    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
